services:
  ui:
    hostname: ui
    build:
      context: ../.devcontainer
      dockerfile: Dockerfile.dev
      args:
        USER_UID: ${USER_UID:-1000}
    volumes:
      - ../:/workspace/ui:cached
    init: true
    command: [ 'sleep', 'infinity' ]
